# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wypata(object):
    def setupUi(self, Wypata):
        Wypata.setObjectName("Wypata")
        Wypata.resize(881, 621)
        self.textBrowser = QtWidgets.QTextBrowser(Wypata)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 741, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(Wypata)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 831, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setStyleSheet("selection-color: rgb(170, 0, 0);\n"
"")
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout.addWidget(self.spinBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setMaximum(9999999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_2.addWidget(self.spinBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(Wypata)
        QtCore.QMetaObject.connectSlotsByName(Wypata)
        Wypata.setTabOrder(self.listWidget, self.pushButton)
        Wypata.setTabOrder(self.pushButton, self.spinBox)
        Wypata.setTabOrder(self.spinBox, self.spinBox_2)
        Wypata.setTabOrder(self.spinBox_2, self.spinBox_3)
        Wypata.setTabOrder(self.spinBox_3, self.textBrowser)

    def retranslateUi(self, Wypata):
        _translate = QtCore.QCoreApplication.translate
        Wypata.setWindowTitle(_translate("Wypata", "Wyplata - System Ekspercki"))
        self.label_4.setText(_translate("Wypata", "Typ pracownika"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Wypata", "Stażysta"))
        item = self.listWidget.item(1)
        item.setText(_translate("Wypata", "Młodszy Specjalista"))
        item = self.listWidget.item(2)
        item.setText(_translate("Wypata", "Specjalista"))
        item = self.listWidget.item(3)
        item.setText(_translate("Wypata", "Starszsy Specjalista"))
        item = self.listWidget.item(4)
        item.setText(_translate("Wypata", "Kierownik Zespołu"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Wypata", "Lata Pracy"))
        self.label_2.setText(_translate("Wypata", "Przepracowanych godzin"))
        self.label_3.setText(_translate("Wypata", "Stawka za godzinę"))
        self.pushButton.setText(_translate("Wypata", "Generuj"))
        #self.listWidget.itemActivated.connect(itemActivated_event)
        self.pushButton.clicked.connect(self.print_setup)

    #def itemActivated_event(item):
    #    print(item.text())

    def print_setup(self):
        print(self.listWidget.currentItem().text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wypata = QtWidgets.QDialog()
    ui = Ui_Wypata()
    ui.setupUi(Wypata)
    Wypata.show()
    sys.exit(app.exec_())
