# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wypata(object):
    def setupUi(self, Wypata):
        Wypata.setObjectName("Wypata")
        Wypata.resize(641, 387)
        self.buttonBox = QtWidgets.QDialogButtonBox(Wypata)
        self.buttonBox.setGeometry(QtCore.QRect(270, 330, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.spinBox = QtWidgets.QSpinBox(Wypata)
        self.spinBox.setGeometry(QtCore.QRect(290, 60, 81, 22))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(Wypata)
        self.label.setGeometry(QtCore.QRect(290, 30, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Wypata)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 141, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(Wypata)
        self.spinBox_2.setGeometry(QtCore.QRect(20, 60, 81, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_3 = QtWidgets.QLabel(Wypata)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.label_3.setObjectName("label_3")
        self.spinBox_3 = QtWidgets.QSpinBox(Wypata)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 110, 81, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton = QtWidgets.QPushButton(Wypata)
        self.pushButton.setGeometry(QtCore.QRect(510, 300, 111, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Wypata)
        self.textBrowser.setGeometry(QtCore.QRect(20, 160, 381, 201))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Wypata)
        self.buttonBox.accepted.connect(Wypata.accept)
        self.buttonBox.rejected.connect(Wypata.reject)
        QtCore.QMetaObject.connectSlotsByName(Wypata)

    def retranslateUi(self, Wypata):
        _translate = QtCore.QCoreApplication.translate
        Wypata.setWindowTitle(_translate("Wypata", "Wyplata - System Ekspercki"))
        self.label.setText(_translate("Wypata", "Lata Pracy"))
        self.label_2.setText(_translate("Wypata", "Przepracowanych godzin"))
        self.label_3.setText(_translate("Wypata", "Stawka za godzinę"))
        self.pushButton.setText(_translate("Wypata", "Generuj Raport"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wypata = QtWidgets.QDialog()
    ui = Ui_Wypata()
    ui.setupUi(Wypata)
    Wypata.show()
    sys.exit(app.exec_())
