# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wypata(object):
    def setupUi(self, Wypata):
        Wypata.setObjectName("Wypata")
        Wypata.resize(780, 565)
        self.textBrowser = QtWidgets.QTextBrowser(Wypata)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 741, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.splitter = QtWidgets.QSplitter(Wypata)
        self.splitter.setGeometry(QtCore.QRect(80, 70, 601, 58))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout.addWidget(self.spinBox_2)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_2.addWidget(self.spinBox_3)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.widget2)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Wypata)
        QtCore.QMetaObject.connectSlotsByName(Wypata)

    def retranslateUi(self, Wypata):
        _translate = QtCore.QCoreApplication.translate
        Wypata.setWindowTitle(_translate("Wypata", "Wyplata - System Ekspercki"))
        self.label_2.setText(_translate("Wypata", "Przepracowanych godzin"))
        self.label_3.setText(_translate("Wypata", "Stawka za godzinę"))
        self.label.setText(_translate("Wypata", "Lata Pracy"))
        self.pushButton.setText(_translate("Wypata", "Generuj"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wypata = QtWidgets.QDialog()
    ui = Ui_Wypata()
    ui.setupUi(Wypata)
    Wypata.show()
    sys.exit(app.exec_())
